<?php $container = $this->container; ?>
<ul class="<?php echo $this->navigation($container)->menu()->getUlClass(); ?>">
    <?php foreach ($container as $page) : ?>
        <?php if (! $this->navigation()->accept($page)) { ?>
            <?php   continue; ?>
        <?php } ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (! $hasChildren) : ?>
            <li class="nav-item<?php echo ($page->isActive()) ? ' active' : ''?>">
                <a
                    class="nav-link"
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != "") : ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                >
                    <?php echo $this->escapeHtml($page->getLabel()); ?>
                </a>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
