<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->title)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
    </head>

    <body>
        <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
            <div class="container">
                <a href="<?php echo $this->url('home') ;?>" class="navbar-brand"><?php echo $this->title; ?></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <?php echo $this->navigation('default')->menu()
                        ->setUlClass("navbar-nav")
                        ->setPartial(['partial/navigation.phtml', 'Application']); ?>
                </div>
            </div>
        </div>

        <div class="container">
            <?= $this->content ?>

            <footer id="footer">
                <div class="row">
                    <div class="col-lg-12">
                        <ul class="list-unstyled">
                            <li class="float-lg-right"><a href="#top">Back to top</a></li>
                            <li>© 2018 Pedro de Oliveira</li>
                            <li><a href="https://github.com/falsovsky/idlerpg-site-ng">site source</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>

        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ?>
        <?= $this->inlineScript() ?>
    </body>
</html>
