<?php $this->headTitle('Player database'); ?>

<?php
$this->headLink()
    ->prependStylesheet("https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css")
    ->prependStylesheet("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css");
$this->headScript()
    ->prependFile("https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js")
    ->prependFile("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js");
?>

<h1>Player database</h1>

<table id="example" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>User</th>
            <th>Level</th>
            <th>Admin</th>
            <th>Class</th>
            <th>Time to level</th>
            <th>Nick!User@Host</th>
            <th>Online</th>
            <th>Total Time Idled</th>
            <th>X Pos</th>
            <th>Y Pos</th>
            <th>Message Penalty</th>
            <th>Nick Penalty</th>
            <th>Part Penalty</th>
            <th>Kick Penalty</th>
            <th>Quit Penalty</th>
            <th>Quest Penalty</th>
            <th>Logout Penalty</th>
            <th>Total Penalty</th>
            <th>Account Created</th>
            <th>Last Login</th>
            <th>Amulet</th>
            <th>Charm</th>
            <th>Helm</th>
            <th>Boots</th>
            <th>Gloves</th>
            <th>Ring</th>
            <th>Leggings</th>
            <th>Shield</th>
            <th>Tunic</th>
            <th>Weapon</th>
            <th>Sum</th>
            <th>Alignment</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>User</th>
            <th>Level</th>
            <th>Admin</th>
            <th>Class</th>
            <th>Time to level</th>
            <th>Nick!User@Host</th>
            <th>Online</th>
            <th>Total Time Idled</th>
            <th>X Pos</th>
            <th>Y Pos</th>
            <th>Message Penalty</th>
            <th>Nick Penalty</th>
            <th>Part Penalty</th>
            <th>Kick Penalty</th>
            <th>Quit Penalty</th>
            <th>Quest Penalty</th>
            <th>Logout Penalty</th>
            <th>Total Penalty</th>
            <th>Account Created</th>
            <th>Last Login</th>
            <th>Amulet</th>
            <th>Charm</th>
            <th>Helm</th>
            <th>Boots</th>
            <th>Gloves</th>
            <th>Ring</th>
            <th>Leggings</th>
            <th>Shield</th>
            <th>Tunic</th>
            <th>Weapon</th>
            <th>Sum</th>
            <th>Alignment</th>
        </tr>
    </tfoot>
</table>

<?php
$script = <<< EOT
    $(document).ready(function() {
        $('th').addClass( 'text-nowrap' );

        $('#example').DataTable({
            ajax: "{$this->url('database-json')}",
            scrollY: '500px',
            scrollX: true,
            scrollCollapse: true,
            deferRender: true,
            paging: false,

            createdRow: function( row, data, dataIndex ) {
                $('td', row).addClass( 'text-nowrap' );
            },

            columns: [
                { data: "nick" },
                { data: "level" },
                { data: "admin" },
                { data: "class" },
                {
                    data: "ttl",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric',
                    }
                },
                { data: "nick_host" },
                { data: "online" },
                {
                    data: "idled",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "x_pos" },
                { data: "y_pos" },
                {
                    data: "msg_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "nick_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "part_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "kick_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "quit_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "quest_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "logout_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "total_pen",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "created",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                {
                    data: "last_login",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "amulet",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "charm",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "helm",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "boots",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "gloves",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "ring",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "leggings",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "shield",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "tunic",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "weapon",
                    type: "num",
                    render: {
                        _: 'display',
                        sort: 'numeric'
                    }
                },
                { data: "sum" },
                { data: "alignment" },
            ],
        });
    });
EOT;
$this->inlineScript()->appendScript($script);
?>
