<?php $this->headTitle('Player Info: ' . $this->nick); ?>

<?php
$this->headScript()
    ->prependFile("/js/hoverDot.js");
?>

<h1>Player Info</h1>

<p>
    <b>User:</b> <?php echo $this->nick; ?><br />
    <b>Class:</b> <?php echo $this->class; ?><br />
    <b>Admin?:</b> <?php echo $this->admin; ?><br />
    <b>Level:</b> <?php echo $this->level; ?><br />
    <b>Next level: </b><?php echo $this->ttl['display']; ?><br />
    <b>Status:</b> <?php echo ($this->online == 'Yes' ? 'Online' : 'Offline'); ?><br />
    <b>Account Created:</b> <?php echo $this->created['display']; ?><br />
    <b>Last login:</b> <?php echo $this->last_login['display']; ?><br />
    <b>Total time idled:</b> <?php echo $this->idled['display']; ?><br />
    <b>Current position:</b> [<?php echo $this->x_pos; ?>,<?php echo $this->y_pos; ?>]<br />
    <b>Alignment:</b> <?php echo $this->alignment; ?>
</p>

<h2>Map</h2>

<canvas id="world-map"
        height="<?php echo $this->dimensions['height']; ?>" width="<?php echo $this->dimensions['width']; ?>"></canvas>


<h2>Items</h2>
<p>
<?php foreach ($this->items as $item) : ?>
    <?php echo $this->playeritem($item, $this->$item['numeric'], $this->$item['unique']); ?>
    <br />
<?php endforeach; ?>
    <br />
    <b>Sum: <?php echo $this->sum; ?></b>
</p>

<h2>Penalties</h2>
<p>
    <?php foreach ($this->penalties as $penalty) : ?>
        <?php $key = $penalty . '_pen'; ?>
        <b><?php echo ucfirst($penalty); ?>:</b> <?php echo $this->$key['display']; ?><br />
    <?php endforeach; ?>
    <br />
    <b>Total: <?php echo $this->total_pen['display']; ?></b>
</p>

<h2>Recent Events</h2>
<?php if (count($this->mod['items']) > 0) : ?>
<p>
    <?php foreach ($this->mod['items'] as $mod) : ?>
        <?php echo $this->event($mod); ?>
        <br/>
    <?php endforeach; ?>
    <br />
    <?php if ($this->mod['link']) : ?>
    <a class="btn btn-primary"
       href="<?php echo $this->url('player-info', ['nick' => $this->nick, 'mod' => '-full-events']); ?>">
        View all Character Events <span class="badge badge-light"><?php echo $this->mod['total']; ?></span>
    </a>
    <?php endif; ?>
</p>
<?php endif; ?>

<?php $script = "
$(document).ready(function () {
    var items = [
        {
            x: " . $this->x_pos . ",
            y: " . $this->y_pos . ",
            text: '" . $this->nick . "',
            color: '#0080e1',
        },
    ];

    $('#world-map').dotHover(items
    , {
        img: '" . $this->map_image . "'
    });
});
";

$this->inlineScript()->appendScript($script);
?>