<?php $this->headTitle('Player Info: ' . $this->nick); ?>

<h1>Player Info</h1>

<p>
    <b>User:</b> <?php echo $this->nick; ?><br />
    <b>Class:</b> <?php echo $this->class; ?><br />
    <b>Admin?:</b> <?php echo $this->admin; ?><br />
    <b>Level:</b> <?php echo $this->level; ?><br />
    <b>Next level:</b><?php echo $this->ttl['display']; ?><br />
    <b>Status:</b> <?php echo ($this->online == 'Yes' ? 'Online' : 'Offline'); ?><br />
    <b>Account Created:</b> <?php echo $this->created['display']; ?><br />
    <b>Last login:</b> <?php echo $this->last_login['display']; ?><br />
    <b>Total time idled:</b> <?php echo $this->idled['display']; ?><br />
    <b>Current position:</b> [<?php echo $this->x_pos; ?>,<?php echo $this->y_pos; ?>]<br />
    <b>Alignment:</b> <?php echo $this->alignment; ?>
</p>

<h2>Map</h2>
<div id="map">
    <img src="<?php echo $this->url('player-map-image', ['nick' => $this->nick]); ?>">
</div>

<h2>Items</h2>
<p>
    <b>amulet:</b> <?php echo $this->amulet['numeric']; ?> <?php echo (isset($this->amulet['unique']) ? '[<font color="#be9256">' .$this->amulet['unique'] . '</font>]' : ''); ?><br />
    <b>boots:</b> <?php echo $this->boots['numeric']; ?> <?php echo (isset($this->boots['unique']) ? '[<font color="#be9256">' .$this->boots['unique'] . '</font>]' : ''); ?><br />
    <b>charm:</b> <?php echo $this->charm['numeric']; ?> <?php echo (isset($this->charm['unique']) ? '[<font color="#be9256">' .$this->charm['unique'] . '</font>]' : ''); ?><br />
    <b>gloves:</b> <?php echo $this->gloves['numeric']; ?> <?php echo (isset($this->gloves['unique']) ? '[<font color="#be9256">' .$this->gloves['unique'] . '</font>]' : ''); ?><br />
    <b>helm:</b> <?php echo $this->helm['numeric']; ?> <?php echo (isset($this->helm['unique']) ? '[<font color="#be9256">' .$this->helm['unique'] . '</font>]' : ''); ?><br />
    <b>leggings:</b> <?php echo $this->leggings['numeric']; ?> <?php echo (isset($this->leggings['unique']) ? '[<font color="#be9256">' .$this->leggings['unique'] . '</font>]' : ''); ?><br />
    <b>ring:</b> <?php echo $this->ring['numeric']; ?> <?php echo (isset($this->ring['unique']) ? '[<font color="#be9256">' .$this->ring['unique'] . '</font>]' : ''); ?><br />
    <b>shield:</b> <?php echo $this->shield['numeric']; ?> <?php echo (isset($this->shield['unique']) ? '[<font color="#be9256">' .$this->shield['unique'] . '</font>]' : ''); ?><br />
    <b>tunic:</b> <?php echo $this->tunic['numeric']; ?> <?php echo (isset($this->tunic['unique']) ? '[<font color="#be9256">' .$this->tunic['unique'] . '</font>]' : ''); ?><br />
    <b>weapon:</b> <?php echo $this->weapon['numeric']; ?> <?php echo (isset($this->weapon['unique']) ? '[<font color="#be9256">' .$this->weapon['unique'] . '</font>]' : ''); ?><br />
    <br />
    <b>sum: <?php echo $this->sum; ?></b>
</p>

<h2>Penalties</h2>
<p>
    <b>kick:</b> <?php echo $this->kick_pen['display']; ?><br />
    <b>logout:</b> <?php echo $this->logout_pen['display']; ?><br />
    <b>msg:</b> <?php echo $this->msg_pen['display']; ?><br />
    <b>nick:</b> <?php echo $this->nick_pen['display']; ?><br />
    <b>part:</b> <?php echo $this->part_pen['display']; ?><br />
    <b>quest:</b> <?php echo $this->quest_pen['display']; ?><br />
    <b>quit:</b> <?php echo $this->quit_pen['display']; ?><br />
    <br />
    <b>total: <?php echo $this->total_pen['display']; ?></b>
</p>

<h2>Recent Character Modifiers</h2>
<?php if (count($this->mod['items']) > 0) : ?>
<p>
    <?php foreach ($this->mod['items'] as $mod) : ?>
    <?php echo $mod . "<br/>"; ?>
    <?php endforeach; ?>
    <br />
    <?php if ($this->mod['link']) : ?>
    [<a href="<?php echo $this->url('player-info', ['nick' => $this->nick, 'mod' => '-full-modifier']); ?>">View all Character Modifiers</a> (<?php echo $this->mod['total']; ?>)]
    <?php endif; ?>
</p>
<?php endif; ?>
