<?php $this->headTitle('Current Quest'); ?>

<h1>Current Quest</h1>

<?php if ($this->quest['title']) : ?>
    <?php $this->headScript()->prependFile("/js/hoverDot.js"); ?>

<p><b>Quest:</b> <?php echo $this->quest['title']; ?></p>

    <?php if ($this->quest['type'] == 1) : ?>
<p><b>Time to completion:</b> <?php echo $this->quest['objective']; ?></p>
    <?php elseif ($this->quest['type'] == 2) : ?>
    <?php $goal['x_pos'] = $this->quest['stages'][$this->quest['objective'] - 1]['x_pos']; ?>
    <?php $goal['y_pos'] = $this->quest['stages'][$this->quest['objective'] - 1]['y_pos']; ?>
    <?php $goal['color'] = $this->quest['stages'][$this->quest['objective'] - 1]['color']; ?>
<p><b>Current goal:</b> [<?php echo $goal['x_pos']; ?>,<?php echo $goal['y_pos']; ?>]</p>
    <?php endif; ?>

    <?php foreach ($this->quest['players'] as $n => $player) : ?>
<p>
    <b>Participant <?php echo ($n + 1); ?>:</b>
    <a href="<?php echo $this->url('player-info', ['nick' => $player['nick']]); ?>"><?php echo $player['nick']; ?></a>
    <br />
    <b>Position:</b> [<?php echo $player['x_pos']; ?>,<?php echo $player['y_pos']; ?>]</p>
    <?php endforeach; ?>

<h2>Quest Map:</h2>
<p>[Questers are shown in blue, current goal in red]</p>

<canvas id="world-map"
        height="<?php echo $this->dimensions['height']; ?>" width="<?php echo $this->dimensions['width']; ?>"></canvas>

    <?php $script = "
$(document).ready(function () {
    var items = ["; ?>

    <?php foreach ($this->quest['players'] as $coord) : ?>
        <?php $script .= "
        {
            x: " . $coord['x_pos'] . ",
            y: " . $coord['y_pos'] . ",
            text: '" . $coord['nick'] . "',
            color: '" . $coord['color'] . "',
        },"; ?>
    <?php endforeach; ?>

    <?php if ($this->quest['type'] == 2) : ?>
        <?php $script .= "
        {
            x: " . $goal['x_pos'] . ",
            y: " . $goal['y_pos'] . ",
            text: 'Goal',
            color: '" . $goal['color'] . "',
        },"; ?>
    <?php endif; ?>

    <?php $script .= "
    ];

    $('#world-map').dotHover(items
    , {
        img: '" . $this->map_image . "'
    });
});
";

    $this->inlineScript()->appendScript($script); ?>

<?php else : ?>
    <p>Sorry, there is no active quest.</p>
<?php endif; ?>
