<?php $this->headTitle('World Map'); ?>

<h1>World Map</h1>
<p>[offline users are red, online users are blue, normal items are orange, unique items are yellow]</p>

<canvas id="world-map"
        height="<?php echo $this->dimensions['height']; ?>" width="<?php echo $this->dimensions['width']; ?>"></canvas>

<?php $script = "
$(document).ready(function () {
    var items = ["; ?>

<?php foreach ($this->coords as $coord) : ?>
    <?php $script .= "
        {
            x: " . $coord['x'] . ",
            y: " . $coord['y'] . ",
            text: '" . $coord['text'] . "',
            color: '" . $coord['color'] . "',
        },"; ?>
<?php endforeach; ?>

<?php $script .= "
    ];

    $('#world-map').dotHover(items
    , {
        img: '" . $this->map_image . "'
    });
});
";

$this->inlineScript()->appendScript($script);
?>
